
const sidebars = Object.assign({
  toolsLStudio: [
    {
      type: "autogenerated",
      dirName: "tools/LStudio", //二级目录
    },
  ],
  toolsLISA: [
    {
      type: "autogenerated",
      dirName: "tools/LISA_LPM", //二级目录
    },
  ],
  mass_production: [
    {
      type: "autogenerated",
      dirName: "tools/mass_production", //二级目录
    },
  ],
  AIsolutionESR: [
    {
      type: "autogenerated",
      dirName: "AIsolution/ESR", //二级目录
    },
  ],
  AIsolutionDSP: [
    {
      type: "autogenerated",
      dirName: "AIsolution/dsp", //二级目录
    },
  ],
  IndustrysolutionCON: [
    {
      type: "autogenerated",
      dirName: "Industrysolution/Smartairconditioning", //二级目录
    },
  ],
  IndustrysolutionCON: [
    {
      type: "autogenerated",
      dirName: "Industrysolution/Conference_calling_solutions", //二级目录
    },
  ],
  Scanning_pen: [
    {
      type: "autogenerated",
      dirName: "Industrysolution/Scanning_pen", //二级目录
    },
  ],
  CloudView_solution: [
    {
      type: "autogenerated",
      dirName: "Industrysolution/CloudView_solution", //二级目录
    },
  ],
}, require('./modulesConfig').sidebars)
module.exports = sidebars;
